name: CommandFilter
main: us.lolice.commandfilter.CommandFilter
version: "${version}"
api-version: "${apiVersion}"
author: keanoi
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:${kotlinVersion}
